# Generated by Django 6.0.3 on 2026-03-23 20:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=4)),
                ('account_number', models.CharField(max_length=8, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='customers.customer')),
            ],
            options={
                'db_table': 'accounts',
                'indexes': [models.Index(fields=['agency', 'account_number'], name='accounts_agency_6f313c_idx')],
            },
        ),
    ]
