# Generated by Django 6.0.3 on 2026-03-23 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('months', models.PositiveIntegerField()),
                ('monthly_interest_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_simulations', to='accounts.account')),
            ],
            options={
                'db_table': 'loan_simulations',
                'ordering': ['-created_at'],
            },
        ),
    ]
